### ISSUE TITLE
Support textDidChange callbacks

### ISSUE THREAD

**Issue by pkbhadkoliya** [kirualex/KAPinField#14]
How to detect if the user has pressed back key after filling the OTP.

Use case 
-- Enable continue button if the user enters OTP (with the required number of digits)
-- Disable continue button if the user presses back since now the OTP is incomplete.

**Comment by kirualex** [comment]
One way would be to use the delegate callback: ` pinField(_ field: KAPinField, didInput character: Character, isValid: Bool)` and check wether `field.text.count` is equal to the expected code length.

**Comment by xinatanil** [comment]
On v4.2.0, and I don't see any `pinField(_ field: KAPinField, didInput character: Character, isValid: Bool)` delegate methods, nor do I see any other delegate methods that would help me with that.

What makes this catastrophic is the fact that setting a `UITextFieldDelegate` or adding a target for `.editingChanged` event also doesn't work, presumably, because KAPinField overrides `text` and doesn't call super's implementation.

**Comment by kevinrenskers** [comment]
I actually have the same problem: I want to enable/disable a continue button based on the PIN field. I did use the pod directly from the master branch but noticed that the new delegate method is not called when the user uses the backspace key.

**Comment by kirualex** [comment]
could you try the new method on the `master` branch?
passing a Character wasn't really good, as we can have backspace, copy-pasting...
